api_login_check:
    path: /api/login_check


register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: POST

loginView:
    path: /loginView
    controller: App\Controller\DefaultController::loginView


createAuthenticatedClient:
    path: /createAuthenticatedClient
    controller: App\Controller\LoginController::createAuthenticatedClient
    methods: POST


api:
    path: /api
    controller: App\Controller\DefaultController::api

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST