#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: POST


api:
    path: /api
    controller: App\Controller\DefaultController::api

login_check:
    path:     /login_check
    methods:  [POST]

a:
    path: /a
    controller: App\Controller\DefaultController::a


register2:
    path: /register2
    controller: App\Controller\LoginController::register2
    methods: POST